# **Notebook for the testing of Neuronal Networks exercises**

# **Exercise 12:** Testing the Dropout layer

12.2. Test the layer with a random input and check if the output shows the desired behaviour.

In [ ]:
from si.neural_networks.layers import Dropout

dropout_layer = Dropout(probability=0.5)
input_data = np.random.rand(5, 10)
dropout_layer.set_input_shape(input_data.shape)  

# Forward propagation during training --> expected to have some zeros due to the mask
output_train = dropout_layer.forward_propagation(input_data, training=True)
print("Output during training:")
print(output_train)

Output during training:
[[1.08752735 0.         0.         0.44951561 0.         1.3261253
  0.         0.         0.         0.        ]
 [1.44273565 0.         1.63477972 0.07118287 1.89823008 0.
  0.         0.         0.         0.68037116]
 [1.59787978 0.         1.48663138 0.         0.36319677 0.
  0.91840551 1.43387143 0.         0.        ]
 [1.28486646 0.490595   0.         0.         0.         0.42708262
  1.78982273 0.17401187 0.         0.        ]
 [0.         0.         0.04019392 0.         1.09263108 0.
  0.         0.24729515 0.62120223 1.08551303]]


In [ ]:
# Forward propagation during inference --> shoulb the same as the input
output_inference = dropout_layer.forward_propagation(input_data, training=False)
if (output_inference == input_data).all():
    print("Output during inference is the same as the input.")

Output during inference is the same as the input.


In [ ]:
# Backward propagation --> by using a dummy error for testing, we should see some zeros in the input error
error = np.ones_like(input_data) 
input_error = dropout_layer.backward_propagation(error)
print("Input error during backpropagation:")
print(input_error)

Input error during backpropagation:
[[1. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1. 0. 0.]
 [1. 1. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 1. 1.]]


In [ ]:
# Output shape that shpuld be the same as the input shape
if dropout_layer.output_shape() == input_data.shape:
    print("Output shape is correct")
else:
    print("Something is wrong: Output shape is incorrect")


Output shape is correct


In [ ]:
# Parameters of the dropout layer - should be 0
if dropout_layer.parameters() == 0:
    print("Parameters: 0")
else:
    print("Something is wrong: dropout layers do not have learnable parameters")

Parameters: 0


# **Exercise 13:** TanhActivation and SoftmaxActivation classes 

In [1]:
import numpy as np
from si.neural_networks.activation import TanhActivation, SoftmaxActivation

# Create some sample inputs
inputs = np.array([[1.0, 2.0, 3.0], [-1.0, -2.0, -3.0], [0.5, 0.0, -0.5]])

# Tanh Activation Test
tanh_layer = TanhActivation()
tanh_output = tanh_layer.forward_propagation(inputs, training=True)
tanh_gradient = tanh_layer.backward_propagation(np.ones_like(inputs))

print("\nTanh Activation Output:\n", tanh_output)
print("Tanh Gradient:\n", tanh_gradient)

# Softmax Activation Test
softmax_layer = SoftmaxActivation()
softmax_output = softmax_layer.forward_propagation(inputs, training=True)

print("\nSoftmax Activation Output:\n", softmax_output)

# Validate softmax outputs are probabilities
print("\nSoftmax Output Sum (should be 1 for each row):\n", np.sum(softmax_output, axis=-1))



Tanh Activation Output:
 [[ 0.76159416  0.96402758  0.99505475]
 [-0.76159416 -0.96402758 -0.99505475]
 [ 0.46211716  0.         -0.46211716]]
Tanh Gradient:
 [[0.41997434 0.07065082 0.00986604]
 [0.41997434 0.07065082 0.00986604]
 [0.78644773 1.         0.78644773]]

Softmax Activation Output:
 [[0.09003057 0.24472847 0.66524096]
 [0.66524096 0.24472847 0.09003057]
 [0.50648039 0.30719589 0.18632372]]

Softmax Output Sum (should be 1 for each row):
 [1. 1. 1.]


# **Exercise 14:** Categorical Cross Entropy

In [2]:
import numpy as np
from si.neural_networks.losses import CategoricalCrossEntropy

# Test data
y_true_binary = np.array([0, 1, 1, 0])
y_pred_binary = np.array([0.1, 0.9, 0.8, 0.2])

y_true_categorical = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
y_pred_categorical = np.array([[0.8, 0.1, 0.1], [0.1, 0.7, 0.2], [0.2, 0.2, 0.6]])

# Test Categorical Cross Entropy
cce = CategoricalCrossEntropy()
print("Categorical Cross Entropy:")
print("Loss:", cce.loss(y_true_categorical, y_pred_categorical))
print("Derivative:", cce.derivative(y_true_categorical, y_pred_categorical))


Categorical Cross Entropy:
Loss: 0.3635480396729776
Derivative: [[-0.41666667  0.          0.        ]
 [ 0.         -0.47619048  0.        ]
 [ 0.          0.         -0.55555556]]


# **Exercise 15:** Adams Class

In [4]:
from si.neural_networks.optimizers import Adam

# Test data
w = np.array([1.0, 2.0, 3.0])
grad_loss_w = np.array([0.1, 0.2, 0.3])

# Test Adam
print("Testing Adam:")
adam = Adam(learning_rate=0.01)
for _ in range(5):
    w = adam.update(w, grad_loss_w)
    print(f"Updated weights: {w}")


Testing Adam:
Updated weights: [0.99 1.99 2.99]
Updated weights: [0.98 1.98 2.98]
Updated weights: [0.97 1.97 2.97]
Updated weights: [0.96 1.96 2.96]
Updated weights: [0.95 1.95 2.95]
